(library
 (name sdl3)
 (public_name sdl3)
 (libraries bigarray-compat ctypes ctypes-foreign)
 (foreign_stubs
  (language c)
  (names sdl3_stubs)
  (flags
   (:include ../sdl3_cflags.sexp)
   -Wno-unused-parameter))
 (c_library_flags (:include ../sdl3_libs.sexp))
 (modules sdl3_consts sdl3_error sdl3_video sdl3_gamepad sdl3_events sdl3_audio sdl3_surface sdl3_render sdl3))
